// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8EiFs-v4Bdb8mAPJqffuF547uFnnBzLQ',
    appId: '1:908829841858:web:731c90fb36b108ea5dde5b',
    messagingSenderId: '908829841858',
    projectId: 'frufi-2e23d',
    authDomain: 'frufi-2e23d.firebaseapp.com',
    storageBucket: 'frufi-2e23d.firebasestorage.app',
    measurementId: 'G-HKNKJMW8J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDe6oCLAiB9yet7shhOuOqtX0f5CRtqbI',
    appId: '1:908829841858:android:170bfd5a7b672b225dde5b',
    messagingSenderId: '908829841858',
    projectId: 'frufi-2e23d',
    storageBucket: 'frufi-2e23d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnSbeZ2g99r5foFuM3z6EtmZg9iQH0EqY',
    appId: '1:908829841858:ios:659ed59ec7495d515dde5b',
    messagingSenderId: '908829841858',
    projectId: 'frufi-2e23d',
    storageBucket: 'frufi-2e23d.firebasestorage.app',
    iosBundleId: 'com.example.frufi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnSbeZ2g99r5foFuM3z6EtmZg9iQH0EqY',
    appId: '1:908829841858:ios:659ed59ec7495d515dde5b',
    messagingSenderId: '908829841858',
    projectId: 'frufi-2e23d',
    storageBucket: 'frufi-2e23d.firebasestorage.app',
    iosBundleId: 'com.example.frufi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8EiFs-v4Bdb8mAPJqffuF547uFnnBzLQ',
    appId: '1:908829841858:web:238f447d960a8d735dde5b',
    messagingSenderId: '908829841858',
    projectId: 'frufi-2e23d',
    authDomain: 'frufi-2e23d.firebaseapp.com',
    storageBucket: 'frufi-2e23d.firebasestorage.app',
    measurementId: 'G-2KB9B9LK0J',
  );
}
